language: python
python:
   - "3.2"
   - "3.3"
   - "3.4"
   - "3.5"
   - "3.6"
   - "3.7"
   - "3.8"
   - "3.9"
   - "3.10"
   - "3.11"
   - "3.12"

install: pip install coveralls

# SDK does not have any external dependencies.
  
script: coverage run --source=familysearch setup.py test

after_success: coveralls
